### ISSUE TITLE
Error Couldn't connect to TW

### ISSUE THREAD

**Issue by mottico32** [hamx0r/ibrest#7]
Hi

I am trying to install the docker container that you built but  i am getting this error : 

> Lenovo-IdeaPad-Y400:~$ docker run hamx0r/ibrest
> 2017-02-08 12:35:18,033 DEBUG [__main__-<module>:361][MainThread] Using IB GW client at: 127.0.0.1:4003
> 2017-02-08 12:35:18,034 ERROR [handlers-error_handler:120][MainThread] ERROR: <error id=-1, errorCode=502, errorMsg=Couldn't connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.>
> 2017-02-08 12:35:18,034 DEBUG [__main__-<module>:392][MainThread] Setting up IBREST at 127.0.0.1:80
> 2017-02-08 12:35:18,037 INFO  [werkzeug-_log:87][MainThread]  * Running on http://127.0.0.1:80/ (Press CTRL+C to quit)

I have the TWS installed i checked that i have the enabled ActiveX and Socket Clients actived ( Edit Menu > Global Configuration > API > Settings )  , but still i have this problem.

these  are the steps that i did :

Ubuntu 16.4

> 1.  Docker Installation.
> 2.  Container Installation ( Via docker pull hamx0r/ibrest )
> 3. TWS Installation.
> 4. Python and Flask insallation ( just in case ).
> 5. TWS Option checking ( Socket Clients )
> 6. docker run hamx0r/ibrest
> 7. error...
> 

If you have an idea what i should do, let me know.

Thank you in advance.

**Comment by hamx0r** [comment]
Hi @mottico32, the `ibrest` Container normally expects to connect to another container running `ibheadless`, which is the IB Gateway running in its own container.  Please see the ibheadless directory and look at its Dockerfile for info about how to get that running.   

There are notes in the main Dockerfile too (for `ibrest`) about how the ibheadless container should be named "ibgw" so that you can _link_ it properly to your `ibrest` Container:

    # From Dockerfile notes:
    docker run -d --restart=always --name ibrest --link ibgw -e "ID_SECRET_KEY=mysecret" -p 443:443 ibrest

If you want to use TWS running on your actual machine, that _should_ work if you follow the comment at the bottom of the Dockerfile:

    # Be sure to set environment params: IBGW_HOST and IBGW_PORT for how to connect to ibgw if you aren't linking per the "run" examples

That means you can skip using the --link arg, and instead pass in some env vars.   You'll want to set IBGW_HOST to the IP if used (i think) as the Docker network gateway (something like 172.17.0.1) and then set IBGW_PORT to whatever port you configure TWS to listen on.   Configure TWS to allow traffic on the same docker gateway IP.   Now, when you start IBREST, it should hopefully connect to TWS.
